# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diffmeanC <- function(x, g) {
    .Call('adaperm_diffmeanC', PACKAGE = 'adaperm', x, g)
}

sumdiffC <- function(x, g) {
    .Call('adaperm_sumdiffC', PACKAGE = 'adaperm', x, g)
}

meandiffC <- function(x, g) {
    .Call('adaperm_meandiffC', PACKAGE = 'adaperm', x, g)
}

random_reassignments_cpp <- function(g, nperm = 1000L) {
    .Call('adaperm_random_reassignments_cpp', PACKAGE = 'adaperm', g, nperm)
}

random_samples_cpp <- function(xs, k, nsam = 1000L) {
    .Call('adaperm_random_samples_cpp', PACKAGE = 'adaperm', xs, k, nsam)
}

combinations_cpp <- function(n, k) {
    .Call('adaperm_combinations_cpp', PACKAGE = 'adaperm', n, k)
}

subsamples_cpp <- function(xs, k) {
    .Call('adaperm_subsamples_cpp', PACKAGE = 'adaperm', xs, k)
}

bincombinations_cpp <- function(p) {
    .Call('adaperm_bincombinations_cpp', PACKAGE = 'adaperm', p)
}

